### ISSUE TITLE
Let every character amsah tech in the amsah tech event.

### ISSUE THREAD

**Issue by AlexanderHarrison** [AlexanderHarrison/TrainingMode-More#33]
Some characters cannot complete the amsah tech because their percents are too high. Good first issue.

We can either:
- Make the percents user controllable (L + DPad up/down). There is functionality built in that already controls this (but only applies to the cpu) which might be helpful.
- Hardcode each character's percent.

**Comment by NickCondron** [comment]
Which character(s) can't? I tested with pichu the lightest character in the game and I can do it. I know at one point not every character was selectable on the CSS for this event, but that has been fixed.

**Comment by AlexanderHarrison** [comment]
I remember it not working with puff when I tried a while ago. Looks like I was just bad.
