### ISSUE TITLE
Save frame advance button preference

### ISSUE THREAD

**Issue by NickCondron** [AlexanderHarrison/TrainingMode-More#38]
I'm used to 20XX and have always used Z for frame advance. It would be useful to save the last used preference and reuse it (I can't be the only one annoyed by this). There might be other options that are "preferential" too and worth saving. Currently some things are stored like eggsercise high score and probably other things.

**Comment by Kounotori-ssbm** [comment]
I'll be glad to be also able to switch On/Off of Frame Advance with a certain input in-game.
