### ISSUE TITLE
Add events menu option to not render certain options

### ISSUE THREAD

**Issue by strabitz** [AlexanderHarrison/TrainingMode-More#58]
Currently, options can be disabled if other options are set to a certain value. For example, the frame advance button option is greyed out and unselectable if frame advance is turned off. I think it’d be a good option to have these not rendered at all to reduce clutter. For example, if techs are set to random, don’t render the chance fields at all
<img width="1092" alt="Screenshot_2024-09-28_at_10 50 38_AM" src="https://github.com/user-attachments/assets/de3867a4-a5a5-46ed-8a2f-0a23d736ea56">

**Comment by NickCondron** [comment]
Another alternative would be to grey them out and have the navigation skip over any greyed out items

**Comment by AlexanderHarrison** [comment]
Fixed by a tech option submenu

**Comment by strabitz** [comment]
The options are already greyed out and skipped if the tech and getup option isn’t set to random. I just think it’d be nicer to not render them at all.
