### ISSUE TITLE
Max SDI frames per hitlag

### ISSUE THREAD

**Issue by strabitz** [AlexanderHarrison/TrainingMode-More#66]
Currently there’s five options for SDI, None, Low, Medium, High, Very High. The percent chance an SDI will occur during a frame of hitlag with these options is 0%, 16%, 25%, 50%, and 100%.

I think there should be a “max SDIs per hitlag” option, since that would let you set up certain scenarios a bit easier, where you’re trying to lab out dealing with an opponent’s SDI, but you don’t want them teleporting as far as they can go.

also change the “Very High” option to “Always”, and maybe move it to the second option in the list after “None”. I think this will be a lot more useful than having a chance for SDIs to occur

**Comment by AlexanderHarrison** [comment]
What are you labbing that requires such large, inhuman SDI amounts?

**Comment by NickCondron** [comment]
I think it would be much more useful to have options for 0 SDI, 1 SDI, 2 SDI. More SDI than that is mostly nonhuman or at least unrealistic for most moves in the game. It's also much more descriptive than the Low, Medium, High options.

**Comment by strabitz** [comment]
I agree, the options are also not helpful for labbing since they are chance-based. That's what I meant by the original issue here
