### ISSUE TITLE
Option to set the chance of a slot occurring in savestate playback

### ISSUE THREAD

**Issue by strabitz** [AlexanderHarrison/TrainingMode-More#73]
If a player creates a recorded savestate to test something like Fox recovery options, it would be very helpful to set the proportion of each of these slots happening. For example, if the player records different Side-B heights for Fox, you can assign the chances of each Side-B height happening.

**Comment by strabitz** [comment]
The logic for this would probably be similar to how we set chances for tech/getup options

**Comment by AlexanderHarrison** [comment]
Whoever implements this, ensure that the chances are exported when saving, and that previously created replays without chances are backwards compatible with this new version.
