### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by NickCondron** [AlexanderHarrison/TrainingMode-More#78]
Currently, the Makefile will not automatically rebuild if a .dat file is added or if a .asm file is removed. Also .s files are not set as dependencies for rebuild. I can foresee developers making a change and then being confused when the project isn't rebuilt. It would be nice to address this potentially by using an alternative like CMake.

**Comment by AlexanderHarrison** [comment]
.s files not being tracked is a bug that can be easily fixed. 
I don't think it's possible to automatically track and compile each dat file, as each file needs to have it's "mode" manually set (evFunction, cssFunction, etc.) when compiling.

I've never written cmake, so I can't speak on how easy the transition would be. All I can say is that I've never heard good things about cmake.
